### ISSUE TITLE
ZIP code search does not zoom to / near zip code

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#100]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
When searching using a ZIP code, map zooms to or near that ZIP code, or otherwise limits the results or scope of the search based on this ZIP. 

### Observed Behavior
When searching using ZIP code, map does not zoom to or near that ZIP code. It zooms to a Citywide view and highlights results (with larger pins) in this zip code. These highlighted pins are hard to distinguish when all results are still being rendered.

#### Proposed Solution
Render all results, but zoom to the location that a user searched for. 

Filter and re-query results based on the map frame (render only the results in the list view that are included in the current map frame).

### Screenshot
![screen shot 2018-01-21 at 9 51 49 pm](https://user-images.githubusercontent.com/719422/35203241-56c99666-fef5-11e7-9d92-107a088804a0.png)

**Comment by timwis** [comment]
Options:
1. Keep current behaviour and simply zoom to the markers inside the zipcode polygon
2. Only show markers inside the zipcode polygon and zoom to those
3. (Perhaps ideal) searching a zipcode simply gets the bounds of the zipcode polygon and zooms to it, and the map always shows all markers in the current viewport (in this case, the rectangle surrounding the zip code polygon)

@sarahall do you know the reasoning behind showing all markers and just making the ones inside the zip code larger? as opposed to only showing the ones inside the zip code

**Comment by andrewviren** [comment]
Agreed. Number 3 is ideal unless the raised pins increase usability per
Sara.

**Comment by timwis** [comment]
Closed by #155
