### ISSUE TITLE
ZIP code / address text box returns valid results from invalid data

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#101]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
If invalid data is input into the address/zip code box no results will return

### Observed Behavior
When inputting invalid data (e.g. "9823892398r432") into the zip code / address box, valid results return.

#### Proposed Solution
If not matches on an address or zip code are found, return no results.

### Screenshot
![screen shot 2018-01-22 at 9 02 41 am](https://user-images.githubusercontent.com/719422/35224646-b070deaa-ff53-11e7-9582-6d2cbf7ad969.png)

**Comment by timwis** [comment]
This _should_ be fixed by #155 but let's test it to be sure. I think if you type `1912` for instance it will still work because AIS recognises that as a valid address somehow. But long numeric strings fail against AIS.
