### ISSUE TITLE
Header and footer do not match mocks

### ISSUE THREAD

**Issue by sarahall** [CityOfPhiladelphia/parks-rec-finder#102]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg9  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Observed Behavior
> Steps to Reproduce

See spec doc p9

### Screenshot
1.A

**Comment by karissademi** [comment]
Fully closed in #144
