### ISSUE TITLE
Add tagline to desktop header

### ISSUE THREAD

**Issue by sarahall** [CityOfPhiladelphia/parks-rec-finder#103]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg9  | /# |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
Add "Search for activities, locations, or zip codes." as a tagline.

### Observed Behavior
> Steps to Reproduce

n/a

### Screenshot
1.A

**Comment by karissademi** [comment]
Closed in #130
