### ISSUE TITLE
Suspiciously few activities for basketball

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#106]
Only 13 activities show up when searching `basketball`, though 177 locations show up. The query for activities uses:
```sql
WHERE (program_is_public)
AND (program_is_approved)
AND (program_is_active)
AND (
  program_name ILIKE '%basketball%'
  OR program_description ILIKE '%basketball%'
)
```
And the query for locations uses:
```sql
WHERE (facility_is_published)
AND (
  facility_description ILIKE '%basketball%'
  OR facility_name ILIKE '%basketball%'
  OR long_name ILIKE '%basketball%'
)
```
@andrewviren does this sound accurate in knack?

**Comment by andrewviren** [comment]
@timwis those are both accurate for now.

**Comment by timwis** [comment]
@andrewviren okay so just to confirm, there's only 13 activities in knack with `basketball` in the name or description? If so we can close this issue.

**Comment by andrewviren** [comment]
Yes. You can close.
