### ISSUE TITLE
Activities in list view appear to be sorted by MyPPR.Program.ProgramNameFull field

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#111]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
Program names in list view are sorted in some sort of logical order.

### Observed Behavior
Filter the app to reach the list view, e.g

1. Click "Educational & Mentoring" activity category button
2. View list of activities. The rendered displayed Program Names are not in any distinguishable order.

#### Proposed Solution

1. Sort activities by distance to search address / zip code / location.

OR 

2. Sort activities by MyPPR.Program.**ProgramName** field. (not ProgramNameFull). This is the field that is prominently displayed in the list view.

### Screenshot
![image](https://user-images.githubusercontent.com/719422/35304240-d1d35928-0062-11e8-979c-5cf932a4e8a3.png)
Finder view Published, "Educational and Mentoring" activities

![image](https://user-images.githubusercontent.com/719422/35304285-f05eef06-0062-11e8-85bb-3029809bf315.png)
Knack view filtered= Published, Active, Approved, "Educational & Mentoring"

**Comment by timwis** [comment]
Just dove in - unexpectedly complicated. Going to move to higher impact issues and come back for now.

**Comment by timwis** [comment]
Fixed
