### ISSUE TITLE
9 facilities have no zip code

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#120]
Just an FYI for @andrewviren, and doesn't really impact the app, but I was looking into whether we could use string comparison for zip code searches instead of polygon joins, and 9 facilities are missing a zip code. Not many, and means that's on the table if necessary. Either way, just a basic data cleanup issue for your backlog.

```json
  [
    {
      "facility_name": "51st & Parkside"
    },
    {
      "facility_name": "Barkan Park"
    },
    {
      "facility_name": "CASE Building"
    },
    {
      "facility_name": "Innyard Park"
    },
    {
      "facility_name": "Korean War Veteran's Memorial"
    },
    {
      "facility_name": "Lemon Hill"
    },
    {
      "facility_name": "Manton Street Park"
    },
    {
      "facility_name": "McMichael Park"
    },
    {
      "facility_name": "West Park"
    }
  ],
```

**Comment by andrewviren** [comment]
Will fix today. String comparison is definitely an option we can consider.
