### ISSUE TITLE
Search Results View 

### ISSUE THREAD

**Issue by bdolly** [CityOfPhiladelphia/parks-rec-finder#14]
View to display Search Results in a filterable list 

- [x] route: `/search?freetext=<free-text>&near=<address-or-zip>&tag=<tag-value>,<tag-value>,...`

# **Sidebar**

- [x] Header 
- [ ] "Clear" all button
- [x] Results summary grammar `Showing <results-count> for <freetext-value> near <address-or-zip-value> that are <nth-tag-value>,  <nth-tag-value>,<nth-tag-value> ...`
- [x] Entity Type Tabs w/ no route navigation 
- [x] Entity List Filters Bar #12 
- [ ]  Resutls Set Entity Type List #15 

# **MAP**
- [x]  plots entity list to pins
- [ ]  on Entity List Item Card hover pin highlights with tooltip

**Comment by timwis** [comment]
I see this in the high priority column but I'm not sure what the action item is?
