### ISSUE TITLE
If location has multiple activities show all onClick of map marker

### ISSUE THREAD

**Issue by sarahall** [CityOfPhiladelphia/parks-rec-finder#140]
### Expected Behavior
In Activities, Athletic category, if a location has multiple activities, these should show onClick of map marker.

Currently only one shows.

### Observed Behavior
> Steps to Reproduce

1. Open athletic
2. Select map marker location with more than one activity (Lawncrest)
![screencapture-localhost-8080-1516998679105](https://user-images.githubusercontent.com/10891276/35459393-fab1ef56-02ad-11e8-9c82-f6bcbba120a1.png)

#### Proposed Solution

[Ref testing protocol 2.1.8.](https://docs.google.com/document/d/1duzm6Nj914sYiUyMSUSoKMWFETPy3C5XSajTEyI5pAs/edit?usp=sharing)

- View map with markers at all locations with this activity category
- Select a specific marker and be shown a tooltip with activity name(s)
   - If marker has one name
       - Select activity name and navigate to that specific activity detail card
   - If marker has 1- 5 activities
      - Select specific activity name and navigate to that specific activity detail card  
   - If marker has 5 or more activities
      - Show first 4 activity names (list alphabetically) and "View more”
           - Select specific activity name, navigate to that specific activity detail card and zoom to specific location marker
           - Select “View more” and navigate to list will all activities at this location

### Screenshot
Mock is for mobile but tooltip styling applies
![mobile_locations-home onclick marker- 1 plus programs](https://user-images.githubusercontent.com/10891276/35459511-71de5664-02ae-11e8-81a9-7fc1b2d810ce.png)

**Comment by timwis** [comment]
Fixed in v2
