### ISSUE TITLE
Contact phone number should show on activity detail card

### ISSUE THREAD

**Issue by sarahall** [CityOfPhiladelphia/parks-rec-finder#141]
### Expected Behavior
Contact phone number should show on activity detail card

### Observed Behavior
![screencapture-localhost-8080-1516999152527](https://user-images.githubusercontent.com/10891276/35459723-596aeaba-02af-11e8-82c1-3e93d72a4546.png)

> Steps to Reproduce
1. Select Athletics
2. Select District 2 basketball league

#### Proposed Solution
Pull in value for contact phone number to show on detail card, match mocks

![programs_detail view-cardioblastfitness copy](https://user-images.githubusercontent.com/10891276/35459797-9e6080d0-02af-11e8-9283-e69db6d6b8aa.png)

**Comment by timwis** [comment]
It doesn't look like the [programs table](https://cityofphiladelphia.carto.com/u/phl/tables/ppr_programs/public) has contact info on it, so we'll need to get it by joining the facilities table. @sarahall will confirm that programs don't have their own phone number.
