### ISSUE TITLE
Link for registration not showing

### ISSUE THREAD

**Issue by sarahall** [CityOfPhiladelphia/parks-rec-finder#143]
Link for registration not showing

### Expected Behavior
If registration is open, link should show under Registration information

### Observed Behavior
http://localhost:8080/#/program/5a562db21faa8455779481a2

#### Proposed Solution
Match mocks
### Screenshot
![programs_detail view-cardioblastfitness copy](https://user-images.githubusercontent.com/10891276/35460810-4193223c-02b3-11e8-8d1b-ed7bc9571861.png)

**Comment by karissademi** [comment]
Closed in #166
