### ISSUE TITLE
Show "Clear all" button if a user selects a filter

### ISSUE THREAD

**Issue by sarahall** [CityOfPhiladelphia/parks-rec-finder#147]
### Expected Behavior
Show "Clear all" button if a user selects a filter

### Observed Behavior
> Steps to Reproduce
http://localhost:8080/parks-rec-finder/#/activities/athletic?fee=Fee&gender=M&days=56fcf33a2b8f3451146ce0fa&days=56fcf3292b8f3451146ce0f8&days=56fcf32eb3d0292214d21d41&days=56fc90e5b67a9db679a60d03&days=56fcf334680e370b56ab5e3a&days=56fcf3238ddf5b391499f6cb&days=56fc90d38041752020119b23&ages=2-99

![screencapture-localhost-8080-parks-rec-finder-1517003115010](https://user-images.githubusercontent.com/10891276/35462094-8f498ad4-02b8-11e8-81a5-d25f8e5d7732.png)

#### Proposed Solution
Match mock
![programs_list view filter open - fee selected](https://user-images.githubusercontent.com/10891276/35462063-77955256-02b8-11e8-83af-74ce0238249e.png)

**Comment by timwis** [comment]
I believe this is fixed in v2
