### ISSUE TITLE
Location name should be included in mobile activity category list

### ISSUE THREAD

**Issue by sarahall** [CityOfPhiladelphia/parks-rec-finder#150]
Location name should be included in mobile activity category list

### Expected Behavior
[ref testing protocol 14.1.6.](https://docs.google.com/document/d/1duzm6Nj914sYiUyMSUSoKMWFETPy3C5XSajTEyI5pAs/edit#)
- View individual card, each contains
   - Name of activity
   - Location name
   - Age range
   - Gender
   - Cost

### Observed Behavior
> Steps to Reproduce
http://localhost:8080/parks-rec-finder/#/activities/athletic
![screencapture-localhost-8080-parks-rec-finder-1517004904263](https://user-images.githubusercontent.com/10891276/35463027-9ff11592-02bc-11e8-9c97-47ce6bcb7735.png)

#### Proposed Solution
Include location name

![mobile_program-category list](https://user-images.githubusercontent.com/10891276/35463032-ab501e74-02bc-11e8-9d37-94f23e136d89.png)

**Comment by karissademi** [comment]
Closed in #171
