### ISSUE TITLE
Clicking finder exits the app

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#154]
It's linked to `/` (which I recommended, I know), but if you click that in production, it takes you to `beta.phila.gov`, which is the `/` of `beta.phila.gov/parks-rec-finder`

**Comment by karissademi** [comment]
I realized it a little too late. I fixed it in https://github.com/CityOfPhiladelphia/parks-rec-finder/pull/144/commits/7d84542385c9f0cc67a92c42753d4af79f25a0e8. Should be in `develop` soon.

**Comment by timwis** [comment]
Hm.. that kinda hard-codes it to the directory name.. I have a feeling there's a more flexible way (that won't work on local dev, for instance), though probably fine for now.
