### ISSUE TITLE
Add "View map" to mobile search results

### ISSUE THREAD

**Issue by sarahall** [CityOfPhiladelphia/parks-rec-finder#159]

**Comment by karissademi** [comment]
Did some investigating on this. It's not a quick fix as I originally thought. Adding the map to each view is trivial, but it won't update correctly without additional entities mapping. I'm going to move off this for now, in favor of more important fixes.

**Comment by sarahall** [comment]
Deprioritizing and adding to backlog -- infrastructure is not set up to easily add, will require more dev work.

**Comment by timwis** [comment]
Pretty sure this is done in v2, right @sarahall ?

**Comment by karissademi** [comment]
Fixed in v2.
