### ISSUE TITLE
Refine filters to match spec

### ISSUE THREAD

**Issue by sarahall** [CityOfPhiladelphia/parks-rec-finder#165]
### Expected Behavior
[7.1.2.1. - 7.2.1.4.](https://docs.google.com/document/d/1duzm6Nj914sYiUyMSUSoKMWFETPy3C5XSajTEyI5pAs/edit?usp=sharing)

Each of the filters so do as follows: 
- Fee is an "or" situation, a user may select "Fee" or "Free". Filtered results will show all programs with matching criteria. 
- Age range is an "and" situation, a user may select one or all of the age ranges. Filtered results will show all programs with Ages within any of the selected ranges.
 - View Gender is an "or" situation, a user may select “Male” “Female” or “All”. Filtered results will show as follows:
    - "Male" is selected, filtered results show all programs with "Male" and "All"
    - "Female" is selected, filtered results show all programs with "Female" and "All"
    - "All" is selected, filtered results show all programs with "Female","Male", and "All"
- Day of week is an "and" situation, a user may select one or all of the days of the week. Filtered results will show all programs with one or all of the days of the week selected.

**Comment by timwis** [comment]
Hm, not sure what the todo is here. The main difference I see above is including "inclusive" vs "exclusive," though IMHO is a bit confusing. Perhaps the "issue" is that some of the filters don't do what you'd expect them to do?

**Comment by sarahall** [comment]
@timwis @karissademi updated issue -- should make sense.

**Comment by karissademi** [comment]
Closed in #174
