### ISSUE TITLE
Facility schedule days are not ordered by weekday, appear to be ordered by MyPPR.FacilitySchedule.FacilityScheduleID

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#182]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
Facility schedule days in Facility Details view are ordered in order of weekday, with Sunday or Monday being first.

### Observed Behavior
Click "recreation centers"
Click "Happy Hollow" or "Simpson" to view those facilities details views

#### Proposed Solution
Order the days in the Facility Details view by MyPPR.Days.WeekdayNumber field.

### Screenshot
![image](https://user-images.githubusercontent.com/719422/35695722-6214e258-0753-11e8-89f6-874acffc8b50.png)
(Saturday is listed first)

![image](https://user-images.githubusercontent.com/719422/35695756-7468b588-0753-11e8-9a0d-ca8bb3b1bd2c.png)
(Saturday is listed second, other days are out of order)

**Comment by sarahall** [comment]
@andrewviren to adjust data in knack.

**Comment by andrewviren** [comment]
@sarahall data has been updated and is sorted in the table as intended. I can test the app and close this issue after the next ETL (tomorrow AM at latest).

**Comment by andrewviren** [comment]
Looks good!
