### ISSUE TITLE
Location name not showing on filtered search 

### ISSUE THREAD

**Issue by Arinblack** [CityOfPhiladelphia/parks-rec-finder#189]
[Spec. Ref.  v1.0.4]  | URL https://beta.phila.gov/parks-rec-finder/#/search?freetext=soccer%20&gender=F&ages=20-55   | App Version v.1 | Browser (version) - chrome | Device hp dell
---------- | --- | ----------- | ------------------------ | ------

### Expected Behavior
I opened the app
I searched "soccer" and "19130" and received 11 activity results. 
From there, I applied filters for "female" and "adult"  and refined the search. 
I expected to be able to click on the result to learn more. 

### Observed Behavior
> Steps to Reproduce

I searched "soccer" and "19130" and received results. 
From there, I applied filters for "female" and "adult"  and refined the search. 
I received 1 result for activity, but I cannot click on it, nor does it show the location name. 

### Screenshot
![image](https://user-images.githubusercontent.com/28628134/35870226-25fa3874-0b2f-11e8-91e5-8977e9448cc9.png)

**Comment by karissademi** [comment]
This will be fixed in https://github.com/CityOfPhiladelphia/parks-rec-finder/pull/186
