### ISSUE TITLE
List view does not render any locations or activities on mobile

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#190]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
After clicking a (locations or activities) category button, a list of that location or activity category is listed. 

### Observed Behavior
(On iPhone SE device, chrome and safari)
Click a location or activity category. Blank area (where list would go) is rendered with option for map view. Map view works. Flipping back to list view from map view does not fix.
### Screenshot
![image](https://user-images.githubusercontent.com/719422/35925532-f4009636-0bf3-11e8-962d-c622373fab13.png)

**Comment by karissademi** [comment]
Closed in #192
