### ISSUE TITLE
Titles and addresses requiring two lines each cross list card border

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#191]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
Longer location titles (>30 char) and addresses fit inside the location list card

### Observed Behavior
Click on "Places to eat"

### Screenshot
![image](https://user-images.githubusercontent.com/719422/35928507-5537d5ac-0bfb-11e8-8cec-ca71a86392d6.png)

**Comment by karissademi** [comment]
Fixed in #192
