### ISSUE TITLE
Search::Address:Zip: return error if zipcode is outside of philadelphia

### ISSUE THREAD

**Issue by bdolly** [CityOfPhiladelphia/parks-rec-finder#2]
hard code an array of zipcodes to check against in the app

**Comment by bdolly** [comment]
Philadelphia zipcodes
-  19128
- 19109
- 19151
- 19153
- 19154
- 19143
- 19145
- 19122
- 19123
- 19102
- 19103
- 19107
- 19126
- 19134
- 19147
- 19127
- 19121
- 19135
- 19120
- 19125
- 19124
- 19104
- 19106
- 19111
- 19112
- 19114
- 19138
- 19115
- 19116
- 19118
- 19119
- 19149
- 19150
- 19152
- 19129
- 19130
- 19131
- 19132
- 19133
- 19136
- 19137
- 19139
- 19140
- 19141
- 19146
- 19142
- 19144
- 19148

**Comment by bdolly** [comment]
above zip codes can be pulled from Carto DB `zip_codes` with 
```
https://phl.carto.com/api/v2/sql?q=SELECT%20code%20FROM%20zip_codes
```

**Comment by timwis** [comment]
Closing in favor of #152
