### ISSUE TITLE
Days of week parameter button disappears after clicking in, out of activity detail card

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#207]
Reference documents
[Spec. Doc.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view?usp=sharing)  | 
[Testing protocol](https://docs.google.com/document/d/1duzm6Nj914sYiUyMSUSoKMWFETPy3C5XSajTEyI5pAs/edit?usp=sharing)

### Observed Behavior
> Steps to Reproduce

1. Search for a keyword or click through activity categories to a list view
2. Add a days of week filter
3. Select an activity to view details
4. Go back to list view
5. The days of the week filter parameter button no longer renders (although results are constant)

### Screenshot
![screen shot 2018-02-23 at 7 15 33 am](https://user-images.githubusercontent.com/719422/36593837-77764a20-1869-11e8-8c40-6f25d1ed2ef0.png)
![screen shot 2018-02-23 at 7 15 44 am](https://user-images.githubusercontent.com/719422/36593842-79a66a64-1869-11e8-94b3-696872cd4ebe.png)
![screen shot 2018-02-23 at 7 15 51 am](https://user-images.githubusercontent.com/719422/36593843-7b3b1a28-1869-11e8-8df1-5f0604436310.png)

**Comment by timwis** [comment]
Fixed in v2
