### ISSUE TITLE
Mobile based "How to use" pop up modal does not scroll

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#208]
Reference documents
[Spec. Doc.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view?usp=sharing)  | 
[Testing protocol](https://docs.google.com/document/d/1duzm6Nj914sYiUyMSUSoKMWFETPy3C5XSajTEyI5pAs/edit?usp=sharing)

### Observed Behavior
> Steps to Reproduce

1. Open "how to use" pop up in mobile view
2. When pop up is open scroll applies to underlying view. Cutoff text below what is currently rendered is not able to be accessed / read.

### Screenshot
![image](https://user-images.githubusercontent.com/719422/36594037-81b5d66c-186a-11e8-83fb-7e775401aecc.png)

**Comment by timwis** [comment]
#223 will take precedence

**Comment by timwis** [comment]
Closing since this modal was rewritten in v2
