### ISSUE TITLE
Location searches render “undefined” in back button in activities detail view

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#210]
Reference documents
[Spec. Doc.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view?usp=sharing)  | 
[Testing protocol](https://docs.google.com/document/d/1duzm6Nj914sYiUyMSUSoKMWFETPy3C5XSajTEyI5pAs/edit?usp=sharing)

### Observed Behavior
> Steps to Reproduce

1. Search for 19119 zip code
2. select any program

### Proposed change
Remove "for undefined". Use "Search results" only in these cases where there is no free text search. 

### Screenshot
![screen shot 2018-02-23 at 7 28 36 am](https://user-images.githubusercontent.com/719422/36594190-2f100c6a-186b-11e8-9336-048f0faa8bbd.png)

**Comment by timwis** [comment]
#222 probably takes precedence for this
