### ISSUE TITLE
Footer cuts off bottom of last list result in desktop view

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#211]
Reference documents
[Spec. Doc.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view?usp=sharing)  | 
[Testing protocol](https://docs.google.com/document/d/1duzm6Nj914sYiUyMSUSoKMWFETPy3C5XSajTEyI5pAs/edit?usp=sharing)

### Observed Behavior
> Steps to Reproduce

View any list in desktop view

View footer overlapping with last list item

### Screenshot

![screen shot 2018-02-23 at 7 31 33 am](https://user-images.githubusercontent.com/719422/36594345-ca6e4294-186b-11e8-8807-6c8c8d77956b.png)

**Comment by timwis** [comment]
Hm, I think this is intended functionality. Since the list could be much longer, the list area is meant to scroll. So the footer is made "sticky" to the bottom. Unless I'm misunderstanding?

**Comment by andrewviren** [comment]
Hi Tim,

The last list item gets cut off even after scrolling all the way down,
regardless of list length. In other words there is no way to read the
bottom part of the last list result card.

Thanks,

Andy

**Comment by andrewviren** [comment]
Actually, this appears to have been resolved.
