### ISSUE TITLE
Need to update AIS developer key

### ISSUE THREAD

**Issue by tswanson** [CityOfPhiladelphia/parks-rec-finder#213]
Reference documents
[Spec. Doc.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view?usp=sharing)  | 
[Testing protocol](https://docs.google.com/document/d/1duzm6Nj914sYiUyMSUSoKMWFETPy3C5XSajTEyI5pAs/edit?usp=sharing)

### Observed Behavior
> Steps to Reproduce

Application is using AIS documentation developer key - 6ba4de64d6ca99aa4db3b9194e37adbf
This key has been created to track AIS use by this application.  Please update to use -
aeec9db5c3d2033149545595dd31c4bf

**Comment by timwis** [comment]
Thanks!
