### ISSUE TITLE
Programs with ProgramSchedule.DateTo before today not being removed from results

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#218]
Reference documents
[Spec. Doc.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view?usp=sharing)  | 
[Testing protocol](https://docs.google.com/document/d/1duzm6Nj914sYiUyMSUSoKMWFETPy3C5XSajTEyI5pAs/edit?usp=sharing)

### Observed Behavior
> Steps to Reproduce

search for "CityWide Futsal League"

One result is rendered in the search results view.

Click on the activity to view the activities details view.

The program information is rendered without the schedule (this program ended March 30)

### Screenshot
![image](https://user-images.githubusercontent.com/719422/38330894-c4ce0df0-381f-11e8-8698-75b3f781a835.png)

**Comment by timwis** [comment]
Fixed in v2

**Comment by sarahall** [comment]
Can this be closed now or wait until v2 releases? @timwis
