### ISSUE TITLE
Cast JSON-like fields to JSON

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#224]
There are a couple fields with string values that appear to be JSON but are malformed JSON. For example:

```javascript
{ site_contact: "{'last': 'Walker', 'title': '', 'middle': '', 'first': 'cameron'}" }
```
I've seen it in:
- `ppr_programs.registration_form_link`
- `ppr_facilities.site_contact`

Any idea why, and whether it can be cast to JSON in the database or in #219? Otherwise we have to parse it client-side, which is rather hacky.

**Comment by timwis** [comment]
@andrewviren explained this is a type of structured knack field. Apparently knack doesn't output this quite in JSON, so he's going to convert them to regular fields. Andy, are you able to convert `ppr_programs.registration_form_link` to a string as well?

Here's what the result currently is:
![screen shot 2018-06-07 at 6 54 23 am](https://user-images.githubusercontent.com/761444/41095532-a63ceb0e-6a1f-11e8-9634-e37b253b3dc5.png)

**Comment by andrewviren** [comment]
Yes. Working on this

**Comment by andrewviren** [comment]
Program.RegistrationFormLink field data type updated to plain text and data updated in Knack production and test apps.  Will update and test in Carto today.
