### ISSUE TITLE
Improve geometry construction query

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#227]
We're currently computing the centroid twice. 

```sql
SELECT
  json_build_array(
    ST_Y(ST_Centroid(ppr_website_locatorpoints.the_geom)), 
    ST_X(ST_Centroid(ppr_website_locatorpoints.the_geom))
  ) AS geometry
```

Is there a way to optimise this? We could use `ST_AsGeoJSON` but then we have to pick out the `coordinates` of each point before passing it to Leaflet. Which isn't a big deal but it would certainly be handy for the API layer to abstract this.

**Comment by awm33** [comment]
@timwis Aren't `ppr_website_locatorpoints.the_geom` points? Why does the centroid need to be computed? This may be left over from using ppr_assets, which were polygons.

**Comment by timwis** [comment]
Wow. Good catch, lol. And sorry you got pinged on vacation! No need to reply to any of these until you're back :)
