### ISSUE TITLE
Zoom map to address or zipcode on search

### ISSUE THREAD

**Issue by bdolly** [CityOfPhiladelphia/parks-rec-finder#23]
When the user searches using the address/zipcode field the map should zoom into either the bounds of the pins inside the zip code or within a 1mile radius of the given address. If address search is used a map marker should be dropped on the given address. If zipcode is provided a polygon from [PPR Assets](https://www.opendataphilly.org/dataset/parks-and-recreation-assets) should be drawn on map.

**Comment by timwis** [comment]
Closed by #155
