### ISSUE TITLE
Aggregate counts in Activity & Location Category views include duplicates

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#242]
Reference documents
Spec. Doc.  v2 (?)
[Testing protocol](https://docs.google.com/document/d/1F2ri2qxT2QKbD13hewY4ogw4BqHaiZpZNG7h3wY4LaM)

### Observed Behavior
> Steps to Reproduce

The aggregate counts for both locations and activities are sums of the location _categories_ and activity _categories_. (Locations categorized, activities categorized.) It could be perceived to be misleading to show a total number of activities or locations if that number includes duplicates.

### Requested solution

Include a count of only the unique activities and locations at the tops of the location category and activity category view.

### Screenshot

![screen shot 2018-05-18 at 7 41 22 am](https://user-images.githubusercontent.com/719422/40232943-ea2e1510-5a6e-11e8-8c96-897a7d676a7e.png)

**Comment by timwis** [comment]
You mean because activities and locations can have multiple categories?

**Comment by timwis** [comment]
Yes I believe that's what you mean. We are indeed just showing the total items per category. So if an item is in more than one category it's counted twice. I could see how this could be a problem: a media outlet covering the app could easily say "Browse the 433 locations..."

The only way I can think of to show the true count is to make 2 more queries/network requests to get the count of activities and locations. It will affect the load time of the main page, I'm afraid, and it's more than a couple minutes' effort. For now I've removed the totals from the Categories page entirely; it's better to not show them than show inaccurate ones. And we're already surfacing the category counts, which are accurate. Frankly we may not even need to add this back, but I'll see what you think about that. This should at least cover us for now.

**Comment by andrewviren** [comment]
Hi @timwis, fine to close. Agreed: accuracy first. I will add to our roadmap for later.
