### ISSUE TITLE
Locations not being filtered by FacilityIsPublished field

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#243]
Reference documents
Spec. Doc. v2 (?)

### Observed Behavior
> Locations not being filtered by FacilityIsPublished = “yes”

See Azalea Garden, Franklin Square. These should NOT be published, have FacilityIsPublished=“no” value in test Knack app

### Screenshot

**Comment by timwis** [comment]
Fixed. Oversight on my part. They're now hidden from the list and search results.
