### ISSUE TITLE
PPR Finder at root is not rendering

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#244]
Reference documents
[Spec. Doc.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view?usp=sharing)  | 
[Testing protocol](https://docs.google.com/document/d/1duzm6Nj914sYiUyMSUSoKMWFETPy3C5XSajTEyI5pAs/edit?usp=sharing)

### Observed Behavior
> Steps to Reproduce
These urls are currently not rendering anything between the header and footer:
	
-	https://beta.phila.gov/parks-rec-finder/#/
-	https://beta.phila.gov/parks-rec-finder/#/activities
-	https://beta.phila.gov/parks-rec-finder/#/locations

### Screenshot
![image](https://user-images.githubusercontent.com/719422/40325164-c4a249be-5d08-11e8-962d-1ece59686ddb.png)

**Comment by karissademi** [comment]
This was a permissions issue. It has been addressed.
