### ISSUE TITLE
Not able to view at least one complete category card in mobile view

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#246]
[Testing protocol](https://docs.google.com/document/d/1OFYL4GYWQ-RogzCmpMYQ5Gm0Vmhr9AJg-I4sbeMIQsU/edit#heading=h.1znmxbrm4710) - version 2
http://ppr-finder-v2.surge.sh
Data: myppr (production database)
Data download date: 5/18/2018

### Observed Behavior
View activity or locations category view in iPhone SE.
There is not enough vertical screen real estate to render at least one activity or location category card.

### Screenshot
![cant see one entire category card](https://user-images.githubusercontent.com/719422/40372384-8edb1360-5db2-11e8-8eff-9fa49f5aa1e5.jpeg)
![cant see one entire category card2](https://user-images.githubusercontent.com/719422/40372389-902507b2-5db2-11e8-9384-87625c2529ca.jpeg)

**Comment by andrewviren** [comment]
Is there a potential content rewrite that can be done to move to one line of call-to-action test  @Darrenef @Arinblack 

Activities:
"Find an activity from these categories."

Locations: 
"Find a location from these categories."

**Comment by Darrenef** [comment]
How about "Choose from the list below to learn more." [or "to explore"]

**Comment by sarahall** [comment]
I'll speak with the team to

1. Decrease the height of the cards
2. change the call to action text.

**Comment by timwis** [comment]
@sarahall another option is to decrease the height of the header on mobile, perhaps making the search be part of the menu
