### ISSUE TITLE
Site contact name is missing from facility detail view

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#248]
[Testing protocol ](https://docs.google.com/document/d/1OFYL4GYWQ-RogzCmpMYQ5Gm0Vmhr9AJg-I4sbeMIQsU/edit#heading=h.jmpcastxx5ad)- version 2
http://ppr-finder-v2.surge.sh
Data: myppr (production database)
Data download date: 5/18/2018

### Observed Behavior
View any facility detail view

### Screenshot
![image](https://user-images.githubusercontent.com/719422/40373911-ee268a68-5db5-11e8-8345-a1c9a9ed9f83.png)

**Comment by sarahall** [comment]
Currently coming from Knack in weird format.
@andrewviren to change the field to text and will update for testing

**Comment by andrewviren** [comment]
Knack app MyPPR.Facility.FacilityContactName field data type changed to text and data updated. Also update in Knack test apps. Will test in Carto today.

**Comment by timwis** [comment]
@andrewviren just to confirm, you changed it in the production knack app, right? I'll just need to update the current (live/v1) app to use the new format. Shouldn't be too difficult; it's more about timing the deployment with when the data sync runs.

**Comment by andrewviren** [comment]
@timwis, yes FaciltyContactName is now plain text in Knack production and test. I was going to manually update some records in Carto if needed.

**Comment by timwis** [comment]
Tested site contact name and registration form link in v2
