### ISSUE TITLE
Programs not being marked 'active' or 'public' by Rec Supervisors.

### ISSUE THREAD

**Issue by Darrenef** [CityOfPhiladelphia/parks-rec-finder#251]
Reference documents
[Spec. Doc.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view?usp=sharing)  | 
[Testing protocol](https://docs.google.com/document/d/1duzm6Nj914sYiUyMSUSoKMWFETPy3C5XSajTEyI5pAs/edit?usp=sharing)

### Observed Behavior
> Programs entered into MyPPR are not marked public or active by Rec Supervisors.  When asked why this is the case, they reply in one of 2 ways:

1) the program is already full (before being posted to MyPPR) or 
2) program doesn't start until a specific date at which time they will post the program.

Research how far in advance programs should be posted to MyPPR/Finder so the public can see the depth and breadth of PPR's programs.

### Screenshot

Message to rec supervisor:

![image](https://user-images.githubusercontent.com/37077239/40561633-e88c9304-602b-11e8-8d9c-b699622e8552.png)

Response from supervisor:

![image](https://user-images.githubusercontent.com/37077239/40561642-f47032b6-602b-11e8-8b0d-46a651500452.png)

**Comment by sarahall** [comment]
@Darrenef @andrewviren Should these programs have the following Registration statuses:
- if full: Registration closed
-if not active: Planning

**Comment by timwis** [comment]
Sorry, I'm not understanding this one. Is this something that needs to change in the application? Or a process-related issue?
