### ISSUE TITLE
rendering hangs with large number of pins

### ISSUE THREAD

**Issue by bdolly** [CityOfPhiladelphia/parks-rec-finder#26]
When navigating to a view that causes leaflet to render a large number of map markers at once the rendering seems to hang. This is possibly due to the fact that leaflet is adding and rendering a large number of markers simultaneously. 

A proposed solution to this is to add a delay between each marker added to the map so that they are added one at a time. This could possibly be done using Rxjs with Vue [Vue-rxjs](https://github.com/vuejs/vue-rx) or delaying each marker getting added to the state.

**Comment by bdolly** [comment]
partially resolved with in v0.2.5 by adding a loading state for user feedback

**Comment by timwis** [comment]
[vue2-leaflet-markercluster](https://github.com/jperelli/vue2-leaflet-markercluster) may be an easy fix

**Comment by timwis** [comment]
Should be resolved by #170
