### ISSUE TITLE
More robust analytics

### ISSUE THREAD

**Issue by karissademi** [CityOfPhiladelphia/parks-rec-finder#265]
Right now, it's only possible to see root-level traffic. It would be nice to see clicks in the UI & direct links. Maybe something like https://www.npmjs.com/package/vue-analytics will work.

**Comment by timwis** [comment]
@karissademi if you open the console while navigating, it should be firing an analytics event for every page per #237 and logging it. Is that not being recorded?

**Comment by karissademi** [comment]
The full URL with query strings aren't coming in on the Google Data Studio dashboard I made, but I am seeing them in GA. Maybe it's just a config issue.
