### ISSUE TITLE
Merge branches

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#266]
@awm33 we need your help. `v2` is an `orphan` branch. Now that it's live, we want it to be `master`, but we'd prefer the `master` branch commit history (and authors) still be there. Our first thought was to rename `master` to `v1`, and rename `v2` to `master`. But there may be a way for it all to be in the same branch, if that sounds like a good idea.

With guidance from a very helpful person in IRC, here's what I attempted:

```
$> git checkout v2
$> git rebase --interactive --onto 1.0.1 --root v2
$> rm -rf *
$> rm .*
$> git checkout 9a1feeeef3703d83420d901b88c3cd2761956762 -- .
$> git add . -A
$> git commit # should have been --amend
$> git rebase --continue
$> git checkout master
$> git merge v2
$> git push origin master # to my fork
```

You can see the commit history of the result of this at [my fork](https://github.com/timwis/parks-rec-finder/commits/master). Or in the terminal via:

```
# log v2 commits
$> git log 1.0.1..HEAD

# log v1 commits
$> git log 1.0.1
```

As you can see in the github UI, this "worked," but the dates are overlapping and all not quite organised correctly. Another idea that was suggested was to merge the branches via `git merge --strategy ours master`. Not sure if that makes more sense, or if we should just stick with the original plan and rename `master` to `v1`. What do you think, @awm33?

**Comment by timwis** [comment]
@karissademi I asked sean and he recommended we just stick to renaming the current `master` to `v1` and `v2` to `master`. I'm going to do that now.

**Comment by karissademi** [comment]
Seems like a most straightforward approach.

**Comment by gsf** [comment]
You know @timwis you can call me @gsf in GitHub land. Glad that direction worked for you!
