### ISSUE TITLE
Time_to not rendering correct 12-hour period (e.g. AM instead of PM) from Carto data

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#284]
https://www.phila.gov/parks-rec-finder/#/activity/summer-day-camp/5c786b9f1cd9395d66c6f3a2
renders "3:30 a.m." instead of "3:30 p.m." as the data is stored in https://cityofphiladelphia.carto.com/u/phl/tables/ppr_program_schedules/public for ID #5c7d899ea17d1a08605cd358

**Comment by karissademi** [comment]
This cannot be replicated.
