### ISSUE TITLE
graceful js promise failure 

### ISSUE THREAD

**Issue by bdolly** [CityOfPhiladelphia/parks-rec-finder#34]
```
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I response to the above be sure that all promises handle failure gracefully

**Comment by timwis** [comment]
Sounds like a webpack config issue, no? Not sure what node.js process would terminate on the client.

**Comment by bdolly** [comment]
@timwis it's a warning that showed it when running the node.js local dev server for vue, vue-styleguidist, and jest testing. The issue is mostly created as a reminder to implement best practices.
