### ISSUE TITLE
Phone number formatting incorrect throughout 

### ISSUE THREAD

**Issue by Arinblack** [CityOfPhiladelphia/parks-rec-finder#44]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL https://cityofphiladelphia.github.io/ppr-finder/#/location/56a8f86a7a8cee5e3a25b0b5 | App Version  0.2.5| Browser  Chrome (version) - Size | Device HP Stream 
---------- | --- | ----------- | ------------------------ | ------
pg  | / |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
Expect phone numbers to comply with standards as (xxx) xxx-xxxx, 

### Observed Behavior
but they read as xxxxxxxxxx. 

### Steps to reproduce

1. Opened page https://cityofphiladelphia.github.io/ppr-finder/#/activities
2. Clicked on first location type
3. Chose "Fish Hatchery" 
4. Observed phone # type. 

#### Proposed Solution

Andy to reformat? A way to format data? 
### Screenshot

Sorry, little blue won't screenshot.

**Comment by bdolly** [comment]
@Arinblack let's run this by Andy to see if Knack can handle this or if it's part of governance. If not it can be handled on the front-end but will be less accurate than having a DB constraint in place

**Comment by andrewviren** [comment]
They appear to be stored to standard. Also, it looks like the json spits out several different formats for this content including one formatted to standard.

**Comment by timwis** [comment]
Fixed in v2
