### ISSUE TITLE
Program Descriptions not being pulled from the Knack App "MyPPR" Program.ProgramDescriptionShort field

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#51]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
Program descriptions that are displayed on Things to do page's Featured Activities are pulled from the ProgramDescriptionShort field in the Program table of the MyPPR knack database.

### Observed Behavior
> Steps to Reproduce

* Go to https://beta.phila.gov/departments/philadelphia-parks-recreation/things-to-do/. 
* Current descriptions are being pulled from the rich-text "ProgramDescription" field. 

1. Opened page 
1. Typed into search Bar
1. Cicked Marder

#### Proposed Solution
Pull these descriptions from the ProgramDescriptionShort field in the Program table of the MyPPR Knack App. 

This new field was also added to the Programs schema in https://github.com/CityOfPhiladelphia/myppr-data-pipeline

### Screenshot
1.A
![capture](https://user-images.githubusercontent.com/719422/34688773-3eae5ed2-f481-11e7-9ea5-28d4e7092e5a.PNG)

**Comment by bdolly** [comment]
closed w/ https://github.com/CityOfPhiladelphia/phila.gov/pull/573
