### ISSUE TITLE
No results for "programming for people with disabilities"

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#53]
https://cityofphiladelphia.github.io/parks-rec-finder/#/activities/programming-for-people-with-disabilities

![screen shot 2018-01-09 at 13 36 03](https://user-images.githubusercontent.com/761444/34736812-2e3408c4-f542-11e7-867c-16dd5dbf9c45.png)

However, the landing page with location types shows 2 items in the icon:
![screen shot 2018-01-09 at 13 35 18](https://user-images.githubusercontent.com/761444/34736802-21876238-f542-11e7-8ef9-8aefe9a247a1.png)

**Comment by bdolly** [comment]
closed w/ f906e76c336f053923370c4075cb5b2c15cff177
