### ISSUE TITLE
Show cursor icon on dropdowns

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#54]
Use CSS `cursor: pointer` to indicate these elements are clickable.

- Activities | Locations links on entry page
- Filters dropdown on activities list
- Activities list on location detail page
- Filter checkboxes/radios/labels
- "Cancel" and "Apply Filters" buttons on the filters dropdown
- Search icon and cancel icon on mobile viewport

**Comment by bdolly** [comment]
closed w/ 482ff9c2bc5fef64bcd0cc840a6f1767808fae44
