### ISSUE TITLE
Registration information has sample language

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#55]
> To sign up or learn more, use the information listed here!

I'm assuming that is sample/lorem ipsum-like text because the page doesn't actually tell you how to register.

![screen shot 2018-01-09 at 13 39 39](https://user-images.githubusercontent.com/761444/34736991-c2dc7a2e-f542-11e7-990a-de3b011cbb20.png)

Also it says "Girls Scout" instead of "Girl Scouts" but I assume that's a typo in the database /cc @andrewviren

**Comment by bdolly** [comment]
There was not sufficient data available from PPR to customize that content so the content team crafted that boilerplate language until proper data was available

**Comment by andrewviren** [comment]
fixed typo. TY
