### ISSUE TITLE
Gender has bracket and quote

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#56]
![screen shot 2018-01-09 at 13 41 24](https://user-images.githubusercontent.com/761444/34737057-f11870f0-f542-11e7-888e-2d8c6e9a654c.png)

> Gender: ["M/F"]

I'm assuming that's not intentional?

**Comment by bdolly** [comment]
closed w/ 482ff9c2bc5fef64bcd0cc840a6f1767808fae44
