### ISSUE TITLE
Content changes 

### ISSUE THREAD

**Issue by Arinblack** [CityOfPhiladelphia/parks-rec-finder#59]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URLhttps://beta.phila.gov/parks-rec-finder/#/activities/educational-&-mentoring | App Version .325| Browser Chrome  - Size | Device - Dell laptop 
---------- | --- | ----------- | ------------------------ | ------

### Expected Behavior
Language would be clear and not repetitive. 

### Observed Behavior

The language isn't as clear as it could be per JA

#### Proposed Solution
Please change the filter text as follows: 

For the category now called "Fee" change to "Cost"
For the category now called "Time of week" change to "Day of week" 
### Screenshot
1.A

**Comment by bdolly** [comment]
closed w/ f7937c690a47b604b8ca208838319b7683236a2a
