### ISSUE TITLE
Low contrast on department logo

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#60]
The teal on white is pretty low contrast. Not sure this would pass our accessibility check. 

![screen shot 2018-01-09 at 13 47 01](https://user-images.githubusercontent.com/761444/34737286-c185acd0-f543-11e7-8807-c1424caa12b7.png)

**Comment by bdolly** [comment]
closed w/ 308b8a34c1b7c3886d7efe4fea1b912cc650b4bc
