### ISSUE TITLE
Content change ZIP code 

### ISSUE THREAD

**Issue by Arinblack** [CityOfPhiladelphia/parks-rec-finder#61]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL https://beta.phila.gov/parks-rec-finder/#/activities | App Version 0.325 | Browser Chrome  - Size | Device Dell 
---------- | --- | ----------- | ------------------------ | ------

### Expected Behavior

ZIP CODE should be two words 
### Observed Behavior
In search bar, the ghosted text reads as "ZIPCODE"
#### Proposed Solution
Change to ZIP CODE 
### Screenshot
![image](https://user-images.githubusercontent.com/28628134/34737352-e5eceb56-f543-11e7-9335-ecc18e49becf.png)

**Comment by bdolly** [comment]
closed w/ f7937c690a47b604b8ca208838319b7683236a2a
