### ISSUE TITLE
Searching only a zip code shows no results

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#62]
From the entry page, type in a zip code and hit enter.
https://cityofphiladelphia.github.io/parks-rec-finder/#/search?zip=19123

<img width="721" alt="screen shot 2018-01-09 at 13 48 36" src="https://user-images.githubusercontent.com/761444/34737361-ecccffb0-f543-11e7-913f-ca73bfa3c249.png">

**Comment by karissademi** [comment]
This will be fixed in https://github.com/CityOfPhiladelphia/parks-rec-finder/pull/97
