### ISSUE TITLE
Zip code search does not appear to have an effect

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#64]
From entry page, type in `tennis` and hit enter. Then type in a zip code and hit enter. The same results display.

Side note: why does only 1 "activity" show for tennis?

**Comment by bdolly** [comment]
searching zipcode re-orders list by distance from zipcode, however no design solution was ever proposed for this view. It also will shrink map pins that are outside of the zipcode. 

A proposed enhancement to this is to add the polygon for the zipcode when searched.

**Comment by timwis** [comment]
Reopening: At the moment, searching a zip code alone (without freetext) returns no results
