### ISSUE TITLE
When there are no activities results, auto-switch to locations

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#65]
From entry page, search volleyball and hit enter
It says "showing 10 results" but no results are shown. You have to click "Locations (10)" to see the results. The template should default to locations if activities is empty.

<img width="990" alt="screen shot 2018-01-09 at 13 53 59" src="https://user-images.githubusercontent.com/761444/34737689-d32c2cec-f544-11e7-86d6-9340958c416a.png">

**Comment by bdolly** [comment]
related to #3

**Comment by timwis** [comment]
@sarahall I'd rank this high priority - thoughts?

**Comment by karissademi** [comment]
Closed in #130
