### ISSUE TITLE
Activity vs program

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#68]
The application calls them "activities" in the copy, but the URL switches from `/activities` to `/program/xyz`.

**Comment by bdolly** [comment]
PPR had changed the language on the tabs to from Programs -> Activites and thus it changed the category page url, however programatically the entity name is `program` as they are pulled from the `ppr_programs` table. We had also added links to beta that use the `/program/xyz` route so the route remained.
