### ISSUE TITLE
Fee frequency is not rendering in Program Detail view or Featured Activity card

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#69]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior

Fee frequency field text (e.g. "total", "per month", "per week", etc.) renders next to fee amount. 

### Observed Behavior

Fee frequency field  is not rendering in program detail view or featured activity card. 

#### Proposed Solution
Add fee frequency text to wherever the fee is published.

### Screenshot
![image](https://user-images.githubusercontent.com/719422/34738100-fd54d162-f545-11e7-9eb6-3b78d53ecb36.png)

**Comment by bdolly** [comment]
closed w/ d230b1374fae0e61192553726f62fae298b44946

**Comment by andrewviren** [comment]
@bdolly  is this changed for Things to do featured activity cards too? I don't see it changed there.
