### ISSUE TITLE
Map Does Not Change Zoom Level When Searching Using Activity And Location Input Boxes

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#72]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior

When I search for both a program and my zip code (or address), I expect the map to zoom to my location and the list of activities to be arranged by proximity to my searched location

### Observed Behavior

Regardless of what zip code or address I input, all activities in the database are displayed in the search results list in alphabetical order. The map does not zoom to the address I input and does not change if I change the address. 

> Steps to Reproduce

1. Opened page
2. Typed "basketball" into search by activity box and "19143" in address or zip code box
3. Hit enter

#### Proposed Solution

Programs should be listed based on distance from my address. The map view should center on my searched location.

**Comment by bdolly** [comment]
closed w/ f73f2b9d5ff41882bdbbd95b56964cb8d2c76d8d
