### ISSUE TITLE
Header missing turquoise bar at the top

### ISSUE THREAD

**Issue by stacyfinnnaren** [CityOfPhiladelphia/parks-rec-finder#74]
![screen shot 2018-01-09 at 3 30 28 pm](https://user-images.githubusercontent.com/16670068/34741853-10f01450-f552-11e7-8f3a-19bdee0a8442.png)
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Observed Behavior
> Steps to Reproduce

1. Opened page
1. Typed into search Bar
1. Cicked Marder

### Screenshot
1.A

**Comment by bdolly** [comment]
incorporated as loading bar
