### ISSUE TITLE
Things to do - Activities - accent line should be blue #2176d2

### ISSUE THREAD

**Issue by stacyfinnnaren** [CityOfPhiladelphia/parks-rec-finder#75]
<img width="111" alt="screen shot 2018-01-09 at 3 41 43 pm" src="https://user-images.githubusercontent.com/16670068/34742315-b773ff98-f553-11e7-8b1d-b660082c2d9d.png">

[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Observed Behavior
> Steps to Reproduce

1. Opened page
1. Typed into search Bar
1. Cicked Marder

### Screenshot
1.A

**Comment by sarahall** [comment]
Only one "results-count-badge" exists
Options:

1. Remove line beneath
2. Create "results-count-badge-location" and "results-count-badge-activity" with respective colors that show on respective category card and list.

Removed bottom-border as temporary fix.

**Comment by karissademi** [comment]
Accent lines removed in #130
