### ISSUE TITLE
Places to go - Locations - Accent line should be Purple 

### ISSUE THREAD

**Issue by stacyfinnnaren** [CityOfPhiladelphia/parks-rec-finder#76]
<img width="115" alt="screen shot 2018-01-09 at 3 45 19 pm" src="https://user-images.githubusercontent.com/16670068/34742543-7afe5440-f554-11e7-9977-df9ba0b7d99a.png">

[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Observed Behavior
> Steps to Reproduce

1. Opened page
1. Typed into search Bar
1. Cicked Marder

### Screenshot
1.A

**Comment by sarahall** [comment]
Only one "results-count-badge" exists
Options:
1. Remove line beneath
2. Create "results-count-badge-location" and "results-count-badge-activity" with respective colors that show on respective category card and list.

**Comment by karissademi** [comment]
Accent lines removed in #130
