### ISSUE TITLE
Purple color needs to change to #A5097E

### ISSUE THREAD

**Issue by stacyfinnnaren** [CityOfPhiladelphia/parks-rec-finder#77]
![screen shot 2018-01-09 at 4 07 03 pm](https://user-images.githubusercontent.com/16670068/34743240-1a92e92e-f557-11e7-9d4f-29b6da483ce0.png)

[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Observed Behavior
> Steps to Reproduce

1. Opened page
1. Typed into search Bar
1. Cicked Marder

### Screenshot
1.A

**Comment by bdolly** [comment]
@stacyfinnnaren please use issue template or issue will not be considered for resolution

**Comment by sarahall** [comment]
Issue is valid -- all purple should match as described.

**Comment by sarahall** [comment]
Need to change map marker color on map and in list

**Comment by timwis** [comment]
@sarahall line 18 & 25 of https://github.com/CityOfPhiladelphia/parks-rec-finder/blob/master/src/store/Marker.js

**Comment by karissademi** [comment]
Closed in #130
