### ISSUE TITLE
Reduce the length of the search bar to match the spec doc

### ISSUE THREAD

**Issue by stacyfinnnaren** [CityOfPhiladelphia/parks-rec-finder#78]
<img width="934" alt="screen shot 2018-01-09 at 4 11 51 pm" src="https://user-images.githubusercontent.com/16670068/34743598-43d0ee2a-f558-11e7-9e9d-f104ed4b02de.png">
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Observed Behavior
> Steps to Reproduce

1. Opened page
1. Typed into search Bar
1. Cicked Marder

### Screenshot
1.A

**Comment by bdolly** [comment]
invalidating as design is responsive
