### ISSUE TITLE
Things to do featured activities cards repeats "AgeHigh" field in age range

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#80]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
Things to do publishes accurate age range on the featured activities cards.

### Observed Behavior
Go to https://beta.phila.gov/departments/philadelphia-parks-recreation/things-to-do/

View age range that duplicates MyPPR.Program.AgeHigh field

#### Proposed Solution

Use MyPPR.Program.AgeLow field as the part of this age range string.

### Screenshot
1.A
![image](https://user-images.githubusercontent.com/719422/34785515-62bd03f8-f5ff-11e7-9f82-7ef31f4b68d6.png)

**Comment by bdolly** [comment]
closed w/ https://github.com/CityOfPhiladelphia/phila.gov/pull/573
