### ISSUE TITLE
MyPPR.ProgramDescriptionShort field not rendering in Program Details View

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#83]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
Program description taken from MyPPR.Program.ProgramDescriptionShort field renders in Program Details view. 

### Observed Behavior
1. identify approved program in Knack with content in ProgramDescriptionShort field
2. Find in finder

#### Proposed Solution
Add program description to program details view

### Screenshot
Current featured activity on Things to do page:

![image](https://user-images.githubusercontent.com/719422/34792362-c6cddee2-f615-11e7-927e-3ab7581b393a.png)

**Comment by bdolly** [comment]
closed w/ e866495748c3e6b095b5f2d80a53974b7847bad9

**Comment by andrewviren** [comment]
@bdolly when will we see this change in demo app?

**Comment by bdolly** [comment]
@andrewviren already there https://cityofphiladelphia.github.io/parks-rec-finder/#/program/5a3c5e2b6c7a015574f7c2e5

As issues get closed they are deployed shortly after, a good way to check on this is to see if the version number in the bottom right of the app has updated
