### ISSUE TITLE
Facility schedules are not rendering on facility details views

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#84]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior

Facility schedules render on facility details views under the heading"regular schedules".

### Observed Behavior
No facility schedules are rendered on facility details view.

#### Proposed Solution
Pull content from MyPPR.FacilitySchedule table to populate on facility details view.

### Screenshot
![image](https://user-images.githubusercontent.com/719422/34797307-ff2b11f0-f625-11e7-88d9-c125fa11aa60.png)

**Comment by bdolly** [comment]
@sarahall was this proposed for `v1.0.0`?

**Comment by sarahall** [comment]
![locations_detail view-onopen-belfield](https://user-images.githubusercontent.com/10891276/35298433-36fb7d7a-0050-11e8-9e29-f52cc18bb28a.png)

See attached mock (also on p27 of spec doc)

**Comment by karissademi** [comment]
@andrewviren Almost all the facilities are showing open times Friday-Monday, 2:00pm to 10:00pm. I'm assuming that's not correct. 

Once the data is verified this will be complete with https://github.com/CityOfPhiladelphia/parks-rec-finder/pull/134

**Comment by karissademi** [comment]
Done in #146
