### ISSUE TITLE
Program Details Views' Registration Information text should use "above" instead of "here"

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#86]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
Program details views' registration information should read "To sign up or learn more, use the contact information listed above."

### Observed Behavior
Currently reads, "To sign up or learn more, use the information listed here!”"

#### Proposed Solution
Change content for all programs.

### Screenshot
![image](https://user-images.githubusercontent.com/719422/34798406-e7bfbee0-f629-11e7-86ae-1e8f4fe2e95b.png)

**Comment by bdolly** [comment]
closed w/ f9154330b584916b97de999d2a943a494db6060d
