### ISSUE TITLE
Get directions link on Facility Details views link to facility lat long in google maps

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#87]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
Get directions link from facility details view sends query to google maps API based on address not lat long

### Observed Behavior
1. Go to facility details view 
2. Click on "get directions" link

#### Proposed Solution
Make the google API call to the address listed. This can more easily be edited and is human-readable once user has opened google maps. 

### Screenshot
![image](https://user-images.githubusercontent.com/719422/34798522-71d0bf26-f62a-11e7-9099-ae283e865bc7.png)

**Comment by timwis** [comment]
Fixed by #119
