### ISSUE TITLE
Logo in finder

### ISSUE THREAD

**Issue by moriamiller** [CityOfPhiladelphia/parks-rec-finder#88]
Would this version of our logo work better than the one you're using now? I can send the EPS file if it will.
![ppr_logo_white_transparency_2000x629](https://user-images.githubusercontent.com/35315738/34801376-6b844a14-f636-11e7-9036-0d83f5ba3063.png)

**Comment by bdolly** [comment]
updated logo w/ a better version in 308b8a34c1b7c3886d7efe4fea1b912cc650b4bc
