### ISSUE TITLE
Two activity category photos do not match the content

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#92]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior

Games & Summer camp button photos do not match their associated content

### Observed Behavior
view activity category list in finder app

#### Proposed Solution

one of the following photos is selected and tested

Games
Bingo
https://www.flickr.com/photos/77365596@N05/37344286262/in/album-72157660952144448/
https://www.flickr.com/photos/77365596@N05/36704530733/in/album-72157660952144448/
Table Tennis
https://www.flickr.com/photos/77365596@N05/26251696200/in/album-72157667332945305/

Summer Camp
Golf Camp
https://www.flickr.com/photos/77365596@N05/26094092255/in/album-72157664202898673/
https://www.flickr.com/photos/77365596@N05/26068163386/in/album-72157664202898673/
https://www.flickr.com/photos/77365596@N05/26094147385/in/album-72157664202898673/
Performing arts camp
https://www.flickr.com/photos/77365596@N05/27630622543/in/album-72157670231577632/
https://www.flickr.com/photos/77365596@N05/28212159396/in/album-72157670231577632/

**Comment by andrewviren** [comment]
@stacyfinnnaren @bdolly  I'm happy to make the change to one of these in Knack, I'm just not sure if there is a particular photo that would work best (size, contrast, layout, etc.) for both Categories.

**Comment by stacyfinnnaren** [comment]
Hey @andrewviren - I updated the Flikr links spreadsheet awhile back with updated photos for these categories based on your callouts. Please use those photos. Thanks
https://docs.google.com/document/d/1kTwSwun1JT99krLgHhCzfc0da11d3ic4v7rmM_-2dYk/edit?ts=5a467a6f

**Comment by andrewviren** [comment]
changed in Knack. Thanks @stacyfinnnaren and sorry.
