### ISSUE TITLE
Images for Locations and Things To Do need to be at 25% so that the labels are accessible and readable

### ISSUE THREAD

**Issue by stacyfinnnaren** [CityOfPhiladelphia/parks-rec-finder#94]
<img width="1008" alt="screen shot 2018-01-12 at 9 06 57 am" src="https://user-images.githubusercontent.com/16670068/34878462-440401e4-f778-11e7-9147-4eeb49332457.png">

[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Observed Behavior
> Steps to Reproduce

1. Opened page
1. Typed into search Bar
1. Cicked Marder

### Screenshot
1.A

**Comment by karissademi** [comment]
Closed in #144
