### ISSUE TITLE
Free text search returns generic (all) results

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#98]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
Free text search filters activities and locations based on keyword regardless of a user's starting point.

### Observed Behavior
Generic (all) results returned when searching from the base url (#/activities) 
"Search Results For" renders at the top of the list view without including the searched-for term.

Addtionally, once an initial search has been executed, a second search (from url "#/search?freetext=") appears to have no response from the app. 

#### Proposed Solution
Have free text / keyword search filter based on keyword or phrase given in the search bar regardless from your starting point in the app. 

### Screenshot
![screen shot 2018-01-21 at 8 50 33 pm](https://user-images.githubusercontent.com/719422/35201874-d919092a-feec-11e7-9e29-4cf54c624464.png)
(nothing follows "...For")

![screen shot 2018-01-21 at 9 09 19 pm](https://user-images.githubusercontent.com/719422/35202222-65bbb9de-feef-11e7-9044-2cae353eb2fc.png)
(app doesn't appear to respond from this URL)

**Comment by timwis** [comment]
Hm, I'm trying to reproduce and I think @karissademi must have resolved this last night (not deployed yet). From a fresh window, I search `basketball` and it shows the 13 activities I expect. Then I type tennis and hit enter and it shows just the 1 tennis activity (another suspiciously low number but it sounds like that's accurate).

**Comment by karissademi** [comment]
Yeah, this should be corrected with https://github.com/CityOfPhiladelphia/parks-rec-finder/pull/104
