### ISSUE TITLE
Design of searched results in activities list view are different from those rendered on click through from category view 

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#99]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
Consistent rendering of activities listings whether you search or click through from the activity categories. 

### Observed Behavior
1. Search using any keyword (see #98 ). Individual activity list view results include Facility listing, but exclude field headers ("Age range:", "Gender:", "Fee:")

2. Click through from any Activity category. Individual activity list view results do NOT include facility listing, but include field headers.

#### Proposed Solution
Make results consistent regardless of how a user gets to a filtered activity list view. 

The former design is preferable _if_ it includes "fee:" and [fee frequency] (e.g. "Fee: $50 total/season" or "Free") as seen on activity detail view. 

### Screenshot
Searched results 
![screen shot 2018-01-21 at 9 14 14 pm](https://user-images.githubusercontent.com/719422/35202344-1b8a075c-fef0-11e7-9e19-87a8a67e0c00.png)
(searched results)

![screen shot 2018-01-21 at 9 18 04 pm](https://user-images.githubusercontent.com/719422/35202409-984ce8c2-fef0-11e7-8c72-a9e6f30cf7cb.png)
(click-through results)

**Comment by andrewviren** [comment]
@sarahall Proposed solution should include "Ages:" and "Gender:" headers as well

**Comment by karissademi** [comment]
Closed in #130
